id: ICA285302
legacy_id: P010423
ocr_import_info:
  bdrc_scan_id: W1KG20999
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T02:39:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T10:31:13.923612+00:00'
last_modified: 2022-08-31 18:31:25.758440
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG20999
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG20999
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོད་ཀྱི་དེབ་ཐེར་དཔྱིད་ཀྱི་རྒྱལ་མོའི་གླུ་དབྱངས།
  author: ཏཱ་ལའི་བླ་མ ༠༥་ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7986404998275496
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I1KG21030:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG21030
      total_pages: 290
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG21030.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7986404998275496
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
